version: "3.9"
services:
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"

  sentio:
    build: ..
    image: sentio-lite:2.0
    depends_on:
      - kafka
    volumes:
      - ../data:/app/data:ro
      - ../logs:/app/logs
    environment:
      - STRATEGY=sigor
      - TEST_DATE=2025-10-22
      - SIM_DAYS=0

  sidecar:
    image: python:3.11-slim
    working_dir: /app
    depends_on:
      - kafka
      - sentio
    volumes:
      - ..:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TOPIC_PREFIX=sentio.
      - RESULTS_PATH=/app/results.json
      - TRADES_PATH=/app/trades.jsonl
      - REPLAY_SPEED_MS=60
      - STRATEGY=SIGOR
      - ENV=MOCK
    command: bash -lc "pip install --no-cache-dir confluent-kafka && python3 tools/kafka_sidecar.py"


