version: "3.9"
services:
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"

  sidecar:
    image: python:3.11-slim
    working_dir: /app
    depends_on:
      - kafka
    volumes:
      - ..:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TOPIC_PREFIX=sentio.
      - PRODUCER_MODE=polygon
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - SYMBOLS=TQQQ,SQQQ,TNA,TZA,UVXY,SVIX,SOXS,SOXL,SPXL,SPXS,FAS,FAZ
      - STRATEGY=SIGOR
      - ENV=LIVE
    command: bash -lc "pip install --no-cache-dir confluent-kafka polygon-api-client && python3 tools/kafka_sidecar.py --mode polygon"


